name: Fetch Wikipedia Articles

on:
  schedule:
    # 日本時間朝9時
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  fetch-articles:
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: ".bun-version"

      - name: Install dependencies
        run: bun install

      - name: Fetch articles
        run: bun run fetch-articles

      - name: Set current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/top-articles.json
          git commit -m "chore: update top articles for ${{ steps.date.outputs.date }}"
          git push 
